theme: jekyll-theme-leap-day
title: React ND Project 2 - Would You Rather
description: Project  by Collins Tshuma
# google_analytics: UA-121627234-7

exclude: [
  Gemfile,
  Gemfile.lock,
  node_modules/,
  Gruntfile.js,
  package-lock.json,
  package.json,
  src/
]